version: "3.7"

services:
  vobe-auth:
    container_name: auth
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "./:/go/src/app"
    command: refresh
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
    - "27017:27017"