POST http://[::1]:8080/login
Content-Type: application/json

{
  "username": "comesa",
  "password": "cock"
}

###


POST http://[::1]:8080/signup
Content-Type: application/json

{
  "username": "tdmux",
  "email": "yeet",
  "password": "yote"
}